import Homeslider from "./Homeslider";
import Homesectiontwo from "./Homesectiontwo";
import Clients from "./Clients";
import Leftsideimagesection from "./Leftsideimagesection";
import Twocolumncomp from "./Twocolumncomp";
import Threecolcardwithrm from "./Threecolcardwithrm";
import RightsideImagewsh from "./RightsideImagewsh";
import Whyushomepage from "./Whyushomepage";
import Ctahome from "./Ctahome";
import Threecolhome from "./Threecolhome";
import Genralslider from "./Genralslider";
import Rightsideimagesection from "./Rightsideimagesection";
import WhyuseApp from "./WhyuseApp";
import LeftsideimageCTA from "./LeftsideimageCTA";
import Cardwithpurledot from "./Cardwithpurledot";
import RightsideimageCTA from "./RightsideimageCTA";
import Heading from "./Heading";
import Paragraph from "./Paragraph";
import LeftImageList from "./LeftImageList";
import RightImageList from "./RightImageList";
import Image from "./Image";
import Cardwithpurpledottc from "./Cardwithpurpledottc";
import Contactus from "./Contactus";
import SeoContact from "./SeoContact";
import SemCards from "./SemCards";
import YoutubeVideo from "./YoutubeVideo";
import PortfolioSection from "./PortfolioSection";

export {Homeslider, Homesectiontwo, Clients, Leftsideimagesection, Twocolumncomp, Threecolcardwithrm, RightsideImagewsh, Whyushomepage, Ctahome, Threecolhome, Genralslider, Rightsideimagesection, WhyuseApp, LeftsideimageCTA , Cardwithpurledot, RightsideimageCTA, Heading, Paragraph, LeftImageList, RightImageList,Image, Cardwithpurpledottc, Contactus, SeoContact, SemCards, YoutubeVideo, PortfolioSection}